{"name": "Проверка получения заказов неавторизованным пользователем", "status": "passed", "start": 1713972015203, "stop": 1713972016478, "uuid": "fdf62745-a80a-4b6c-8f2d-4d86ebdb5189", "historyId": "28f8cd95e3ee05704702c8529b47a0b3", "testCaseId": "28f8cd95e3ee05704702c8529b47a0b3", "fullName": "tests.test_get_order.TestGetOrder#test_get_orders_not_authorization_user_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order"}, {"name": "subSuite", "value": "TestGetOrder"}, {"name": "host", "value": "DESKTOP-TQ0O0FL"}, {"name": "thread", "value": "7644-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order"}]}