{"name": "Проверка ошибки создания пользователя, который уже зарегистрирован.", "status": "passed", "start": 1713972040470, "stop": 1713972040981, "uuid": "0362c6d6-53da-497c-97b2-0728c576c209", "historyId": "7a91196f34420e8ee1281a34acea15cd", "testCaseId": "7a91196f34420e8ee1281a34acea15cd", "fullName": "tests.test_registr.TestRegistr#test_creating_double_user_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_registr"}, {"name": "subSuite", "value": "TestRegistr"}, {"name": "host", "value": "DESKTOP-TQ0O0FL"}, {"name": "thread", "value": "7256-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_registr"}]}